CREATE TABLE `seo_keywords`(
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `keyword` INT(255) NOT NULL,
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NULL DEFAULT NULL,
    `deleted_at` DATETIME NULL DEFAULT NULL,
    PRIMARY KEY(`id`)
) ENGINE = InnoDB;

ALTER TABLE `seo_keywords` CHANGE `keyword` `keyword` VARCHAR(255) NOT NULL;